"""Utilities module for 3D potential field prediction."""

from .masking import (
    create_muscle_mask,
    create_singularity_mask,
    create_combined_mask,
    WeightedMaskedMSELoss,
    GradientLoss,
    CombinedLoss,
    NormalizedMSELoss,
    LogCoshLoss,
    PDEResidualLoss,
    SpectralSmoothingLoss,
    TotalVariationLoss,
)
from .metrics import (
    mse,
    rmse,
    mae,
    relative_l2_error,
    max_error,
    compute_all_metrics,
    compute_region_wise_metrics,
    compute_all_metrics_extended,
    compute_scale_metrics,
    compute_smoothness_metrics,
    compute_diagnostic_metrics,
    gradient_norm,
    parameter_norm,
)
from .visualization import (
    save_validation_figure,
    plot_loss_curves,
    create_comprehensive_visualization,
    create_3d_surface,
)
from .training import (
    EarlyStopping,
    ExperimentTracker,
    save_checkpoint,
    load_checkpoint,
)

__all__ = [
    "create_muscle_mask",
    "create_singularity_mask",
    "create_combined_mask",
    "WeightedMaskedMSELoss",
    "GradientLoss",
    "CombinedLoss",
    "NormalizedMSELoss",
    "LogCoshLoss",
    "PDEResidualLoss",
    "SpectralSmoothingLoss",
    "TotalVariationLoss",
    "mse",
    "rmse",
    "mae",
    "relative_l2_error",
    "max_error",
    "compute_all_metrics",
    "compute_region_wise_metrics",
    "compute_all_metrics_extended",
    "compute_scale_metrics",
    "compute_smoothness_metrics",
    "compute_diagnostic_metrics",
    "gradient_norm",
    "parameter_norm",
    "save_validation_figure",
    "plot_loss_curves",
    "create_comprehensive_visualization",
    "create_3d_surface",
    "EarlyStopping",
    "ExperimentTracker",
    "save_checkpoint",
    "load_checkpoint",
]
